import fs from 'node:fs';
import vm from 'node:vm';
import { performance } from 'node:perf_hooks';

// Focused RUSHER search: retain its factory/pressure identity and vary only its
// opening, economy, combat, defense, and capture thresholds.
globalThis.window=globalThis;
for(const file of ['public/game/domain/random.js','public/game/domain/arena-config.js','public/game/domain/arena/match-engine.js'])vm.runInThisContext(fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),{filename:file});
const {BOTS,CIVILIZATIONS,GAME_CONFIG}=FactoryWars.Config,Match=FactoryWars.Match,bots=Object.keys(BOTS),civs=Object.keys(CIVILIZATIONS),baseDecision=Match.prototype.baseBotDecision,currentDecision=Match.prototype.botDecision;
const genes={factoryAfter:[0,30],preFactoryEcoUntil:[0,22],growthFactor:[1.2,2.25],ecoAfterFactory:[20,100],ecoUntil:[55,160],ecoMaxLevel:[1,3],attackAfter:[10,90],largeAfter:[55,150],largeBank:[230,680],defendHP:[220,500],defendThreshold:[10,190],captureAfter:[20,115],captureChance:[.1,.85],captureShield:[80,380],counterEcoDelay:[0,30],counterEcoChance:[.1,.9],sabotageAfter:[40,135],sabotageChance:[.1,.75]};
const ints=new Set(['factoryAfter','preFactoryEcoUntil','ecoAfterFactory','ecoUntil','ecoMaxLevel','attackAfter','largeAfter','largeBank','defendHP','defendThreshold','captureAfter','captureShield','counterEcoDelay','sabotageAfter']);
let state=0x52555348;const rng=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;},clamp=(x,r)=>Math.max(r[0],Math.min(r[1],x));
function randomGenome(){const g={};for(const[k,r]of Object.entries(genes)){const x=r[0]+rng()*(r[1]-r[0]);g[k]=ints.has(k)?Math.round(x):Number(x.toFixed(2));}return g;}
function mutate(g,power=1){const out={...g};for(const[k,r]of Object.entries(genes))if(rng()<.38){const x=out[k]+(rng()+rng()+rng()-1.5)*(r[1]-r[0])*.2*power;out[k]=ints.has(k)?Math.round(clamp(x,r)):Number(clamp(x,r).toFixed(2));}return out;}
function rusherPolicy(p,g){const C=GAME_CONFIG,o=this.other(p),t=this.t,remain=C.matchDuration-t,can=k=>this.can(p,k),act=k=>this.act(p,k),threat=this.incoming(p),net=threat.reduce((s,x)=>s+x.damage,0)-this.shield(p),recent=this.events.filter(e=>e.player===o.id&&t-e.t<=36&&e.type!=='state_sample'),lastEco=[...recent].reverse().find(e=>e.type==='econ_upgrade'),growthPayback=p.level>=4?Infinity:this.cost(p,'eco')/(C.economicLevels[p.level]-C.economicLevels[p.level-1]),grow=()=>can('eco')&&remain>growthPayback*g.growthFactor;
 const defend=()=>{if(net<g.defendThreshold&&!(threat.length&&p.hp<g.defendHP))return false;if(net>155&&can('defLarge'))return act('defLarge');return can('defSmall')&&act('defSmall');};
 const attack=preferLarge=>{if(!p.factory)return false;if(preferLarge&&p.bank>=g.largeBank&&can('large'))return act('large');return can('small')&&act('small');};
 const capture=()=>can('capture')&&this.owner!==p.id&&remain>29&&act('capture');
 // Emergency defense, then keep the RUSHER factory-first opening.
 if(defend())return true;
 if(!p.factory){if(t<g.preFactoryEcoUntil&&p.level===1&&p.bank>=this.cost(p,'eco')+this.cost(p,'factory')+45&&grow()&&act('eco'))return true;if(t>=g.factoryAfter&&can('factory')&&act('factory'))return true;}
 // Punish visible economic investment and attacks with affordable pressure.
 if(lastEco&&p.factory&&t-lastEco.t>=g.counterEcoDelay&&this.rand()<g.counterEcoChance&&attack(t>=g.largeAfter))return true;
 if(p.factory&&t>=g.attackAfter&&attack(t>=g.largeAfter))return true;
 if(p.factory&&t>=g.ecoAfterFactory&&t<g.ecoUntil&&p.level<g.ecoMaxLevel&&grow()&&act('eco'))return true;
 if(t>=g.captureAfter&&this.shield(o)>=g.captureShield&&this.rand()<g.captureChance&&capture())return true;
 if(t>=g.captureAfter&&this.owner!==p.id&&this.rand()<g.captureChance*.45&&capture())return true;
 if(t>=g.sabotageAfter&&lastEco&&this.rand()<g.sabotageChance&&can('sabotage')&&act('sabotage'))return true;
 return false;
}
Match.prototype.botDecision=function(p){const mode=p.rusherMode||'native';if(mode==='current')return currentDecision.call(this,p);if(mode==='calibrated'){p.nativeGenome={};return baseDecision.call(this,p);}const saved=this.calibratedBotDecision;this.calibratedBotDecision=()=>false;if(mode==='candidate')rusherPolicy.call(this,p,p.rusherGenome);else{p.nativeGenome={};baseDecision.call(this,p);}this.calibratedBotDecision=saved;};

const POP=Number(process.env.RUSHER_POPULATION||32),GENS=Number(process.env.RUSHER_GENERATIONS||8),REPS=Number(process.env.RUSHER_TRAIN_REPS||3),HOLDOUT=Number(process.env.RUSHER_HOLDOUT_REPS||16),poolModes=['native','calibrated','current'];
const start=performance.now();let evaluations=0,searchMatches=0,best=null;
function play(seed,opponent,mode,genome,oppMode,civA,civB,first){const m=new Match({mode:'bots',civA,civB,botA:first?'RUSHER':opponent,botB:first?opponent:'RUSHER'},seed),rp=m.players.find(p=>p.id===(first?'A':'B')),op=m.players.find(p=>p.id===(first?'B':'A'));rp.rusherMode=mode;op.rusherMode=oppMode;if(mode==='candidate')rp.rusherGenome=genome;let n=0;while(!m.ended&&n++<1200)m.step(.5,true);return m.winner===rp.id?1:m.winner===null?.5:0;}
function evaluate(g,gen,ix){let total=0,by={};for(let oi=0;oi<bots.length;oi++){const opp=bots[oi];if(opp==='RUSHER')continue;let points=0;for(let mi=0;mi<poolModes.length;mi++)for(let r=0;r<REPS;r++){const seed=330000000+gen*1000000+oi*10000+mi*100+r,ca=civs[(r+oi)%civs.length],cb=civs[(r*3+oi+1)%civs.length];points+=play(seed,opp,'candidate',g,poolModes[mi],ca,cb,true);points+=play(seed,opp,'candidate',g,poolModes[mi],cb,ca,false);}by[opp]=points/(REPS*poolModes.length*2);total+=points;}const mean=total/(8*REPS*poolModes.length*2),worst=Math.min(...Object.values(by));return{genome:g,mean,worst,fitness:.75*mean+.25*worst,by};}
let population=Array.from({length:POP},randomGenome);
for(let gen=0;gen<GENS;gen++){const ranked=population.map((g,i)=>evaluate(g,gen,i)).sort((a,b)=>b.fitness-a.fitness);evaluations+=ranked.length;searchMatches+=ranked.length*8*poolModes.length*REPS*2;if(!best||ranked[0].fitness>best.fitness)best=ranked[0];const next=ranked.slice(0,6).map(x=>x.genome);while(next.length<POP)next.push(mutate(ranked[Math.floor(rng()*Math.min(12,ranked.length))].genome,gen<3?1:.7));population=next;}
const seedFamilies={prior:97000000,fresh:240000000},validation={};let validationMatches=0;
for(let oi=0;oi<bots.length;oi++){const opp=bots[oi];if(opp==='RUSHER')continue;validation[opp]={};for(const oppMode of poolModes){validation[opp][oppMode]={};for(const[family,base]of Object.entries(seedFamilies)){const scores={native:0,current:0,candidate:0};for(let r=0;r<HOLDOUT;r++){const seed=base+oi*100000+poolModes.indexOf(oppMode)*10000+r,ca=civs[(r+oi)%civs.length],cb=civs[(r*3+2)%civs.length];for(const side of [true,false]){const x=side?ca:cb,y=side?cb:ca;scores.native+=play(seed,opp,'native',null,oppMode,x,y,side);scores.current+=play(seed,opp,'current',null,oppMode,x,y,side);scores.candidate+=play(seed,opp,'candidate',best.genome,oppMode,x,y,side);validationMatches+=3;}}validation[opp][oppMode][family]=Object.fromEntries(Object.entries(scores).map(([k,v])=>[k,Number((v/(HOLDOUT*2)).toFixed(4))]));}}}
const avg=(mode,family=null)=>{const a=[];for(const opp of Object.keys(validation))for(const om of poolModes)for(const sf of Object.keys(seedFamilies))if(family===null||family===sf)a.push(validation[opp][om][sf][mode]);return a.reduce((s,x)=>s+x,0)/a.length;};
const perOpponent={};for(const opp of Object.keys(validation)){perOpponent[opp]={};for(const m of ['native','current','candidate']){const a=[];for(const om of poolModes)for(const sf of Object.keys(seedFamilies))a.push(validation[opp][om][sf][m]);perOpponent[opp][m]=a.reduce((s,x)=>s+x,0)/a.length;}}
const elapsed=Number(((performance.now()-start)/1000).toFixed(2));
const result={title:'Focused RUSHER native-branch optimization',createdAt:new Date().toISOString(),method:'Search targets RUSHER only. The candidate retains the RUSHER factory-first identity and adapts economy, attack, defense, capture, and sabotage thresholds. It faces all eight other strategies in native, calibrated, and current forms; paired sides and rotating civilizations. Validation uses the previous held-out seed family plus a fresh family.',budget:{elapsedSeconds:elapsed,maxSeconds:180,population:POP,generations:GENS,trainingRepetitionsPerOpponentModeAndSide:REPS,validationRepetitionsPerOpponentModeAndSide:HOLDOUT,candidateEvaluations:evaluations,searchMatches,validationMatches},genome:best.genome,search:{mean:best.mean,worst:best.worst,byOpponent:best.by},validation:{mean:{native:avg('native'),current:avg('current'),candidate:avg('candidate')},bySeed:Object.fromEntries(Object.keys(seedFamilies).map(sf=>[sf,Object.fromEntries(['native','current','candidate'].map(m=>[m,avg(m,sf)]))])),perOpponent,matchups:validation}};
fs.writeFileSync(new URL('./rusher_focused_results.json',import.meta.url),JSON.stringify(result,null,2));
const pct=n=>`${(n*100).toFixed(1)}%`,lines=['# Optimización enfocada de RUSHER','',`- Tiempo: **${elapsed}s** (límite: 180s).`,`- Búsqueda: ${evaluations} evaluaciones, ${searchMatches.toLocaleString('es-AR')} partidas.`,`- Validación: ${validationMatches.toLocaleString('es-AR')} partidas en dos familias de semillas.`,`- Rivales: los otros ocho bots, en versiones nativas, calibradas y actuales.`,`- La candidata mantiene una apertura centrada en fábrica y presión; ajusta sus propias reglas.`,`- Puntuación: victoria=1, empate=0,5, derrota=0.`, '', '| Versión | Media conjunta | Semilla previa | Semilla nueva |','|---|---:|---:|---:|',`| Nativa | ${pct(avg('native'))} | ${pct(avg('native','prior'))} | ${pct(avg('native','fresh'))} |`,`| Actual | ${pct(avg('current'))} | ${pct(avg('current','prior'))} | ${pct(avg('current','fresh'))} |`,`| Nueva RUSHER | ${pct(avg('candidate'))} | ${pct(avg('candidate','prior'))} | ${pct(avg('candidate','fresh'))} |`,'','## Resultado por rival',''];
for(const[opp,x]of Object.entries(perOpponent))lines.push(`- **${opp}:** nativo ${pct(x.native)}, actual ${pct(x.current)}, nueva ${pct(x.candidate)}.`);lines.push('','## Parámetros encontrados','',...Object.entries(best.genome).map(([k,v])=>`- ${k}: ${v}`),'','Solo conviene promover la candidata si mejora frente a la versión actual en ambas semillas y no abre un counter severo.','');
fs.writeFileSync(new URL('./rusher_focused_results.md',import.meta.url),lines.join('\n'));
console.log(JSON.stringify({elapsedSeconds:elapsed,evaluations,searchMatches,validationMatches,genome:best.genome,validation:result.validation},null,2));
