import fs from 'node:fs';
import vm from 'node:vm';
import { performance } from 'node:perf_hooks';

// Search native branch parameters per strategy (no shared decision order).
globalThis.window=globalThis;
for(const file of ['public/game/domain/random.js','public/game/domain/arena-config.js','public/game/domain/arena/match-engine.js'])vm.runInThisContext(fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),{filename:file});
const {BOTS,CIVILIZATIONS}=FactoryWars.Config,Match=FactoryWars.Match,bots=Object.keys(BOTS),civs=Object.keys(CIVILIZATIONS);
const baseDecision=Match.prototype.baseBotDecision,currentDecision=Match.prototype.botDecision;
const schemas={
 GREEDY:{greedyGrowth:[1.15,2.15],greedyEcoUntil:[105,190],greedyFactoryAfter:[15,75],greedyCaptureAfter:[45,125],greedyCaptureChance:[.25,.9],greedyAttackAfter:[75,145],greedySabotageAfter:[55,135],greedySabotageChance:[.15,.75],greedyLateAttackAfter:[135,195]},
 RUSHER:{rusherFactoryAfter:[0,35],rusherDefendHP:[220,480],rusherEcoAfter:[30,105],rusherEcoReserve:[50,220],rusherGrowth:[1.2,2.2],rusherCaptureShield:[100,400],rusherLargeAfter:[75,160],rusherLargeReserve:[200,500],rusherCaptureAfter:[55,125]},
 TURTLE:{turtleGrowth:[1.25,2.3],turtleEcoUntil:[80,165],turtleShieldBelow:[60,220],turtleShieldBank:[80,260],turtleShieldAfter:[0,60],turtleFactoryAfter:[25,90],turtleCaptureAfter:[45,120],turtleAttackAfter:[90,175],turtleSabotageAfter:[75,155],turtleSabotageChance:[.15,.85]},
 TEMPO:{tempoFactoryAfter:[0,55],tempoPunishEconomyCount:[0,3],tempoGrowth:[1.2,2.4],tempoEcoUntil:[70,155],tempoCaptureAfter:[25,95],tempoCaptureChance:[.1,.8],tempoAttackAfter:[60,145],tempoSabotageAfter:[45,130],tempoSabotageChance:[.1,.8]},
 ADAPTIVE:{adaptiveDefenseLead:[0,3],adaptiveDefenseGrowth:[1.2,2.3],adaptiveGrowth:[1.2,2.3],adaptiveEcoUntil:[85,170],adaptiveFactoryAfter:[0,65],adaptiveCaptureChance:[.1,.8],adaptiveAttackAfter:[35,105],adaptiveLargeAfter:[80,165],adaptiveSabotageChance:[.1,.8]},
 RANDOM:{randomActionChance:[.25,1]},
 BALANCED:{balancedGrowth:[1.2,2.3],balancedEcoUntil:[75,160],balancedEcoMaxLevel:[2,4],balancedFactoryAfter:[0,45],balancedCaptureAfter:[20,90],balancedCaptureChance:[.1,.8],balancedAttackAfter:[25,100],balancedLargeReserve:[20,180],balancedSabotageChance:[.05,.6],balancedFallbackGrowth:[1.1,2.2]},
 HOARDER:{hoarderFactoryAfter:[0,75],hoarderFactoryBank:[220,500],hoarderHoldBank:[300,750],hoarderHoldUntil:[90,210],hoarderEcoMaxLevel:[2,4],hoarderGrowth:[1.15,2.25],hoarderCaptureAfter:[35,125],hoarderCaptureChance:[.1,.8]},
 SABOTEUR:{saboteurGrowth:[1.2,2.2],saboteurEcoUntil:[90,180],saboteurSabotageAfter:[0,85],saboteurFactoryAfter:[20,90],saboteurCaptureAfter:[35,115],saboteurCaptureChance:[.2,.9],saboteurAttackAfter:[85,175]},
};
const intNames=new Set(Object.keys(schemas).flatMap(k=>Object.keys(schemas[k]).filter(x=>!x.toLowerCase().includes('chance')&&!x.toLowerCase().includes('growth')&&!x.toLowerCase().includes('probability'))));
let rngState=0x4e415449;const rng=()=>{rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;return rngState/4294967296;};
const clamp=(n,r)=>Math.max(r[0],Math.min(r[1],n));
function randomGenome(bot){const out={};for(const[k,r]of Object.entries(schemas[bot])){const n=r[0]+rng()*(r[1]-r[0]);out[k]=intNames.has(k)?Math.round(n):Number(n.toFixed(2));}return out;}
function mutate(bot,g,power=1){const out={...g};for(const[k,r]of Object.entries(schemas[bot]))if(rng()<.4){const n=out[k]+(rng()+rng()+rng()-1.5)*(r[1]-r[0])*.2*power;out[k]=intNames.has(k)?Math.round(clamp(n,r)):Number(clamp(n,r).toFixed(2));}return out;}
Match.prototype.botDecision=function(p){const mode=p.searchMode||'native';if(mode==='current'){p.nativeGenome={};return currentDecision.call(this,p);}if(mode==='calibrated'){p.nativeGenome={};return baseDecision.call(this,p);}const saved=this.calibratedBotDecision;this.calibratedBotDecision=()=>false;p.nativeGenome=mode==='candidate'?p.searchGenome:{};baseDecision.call(this,p);this.calibratedBotDecision=saved;};
const POP=Number(process.env.NATIVE_POPULATION||10),GENS=Number(process.env.NATIVE_GENERATIONS||4),REPS=Number(process.env.NATIVE_TRAIN_REPS||2),HOLDOUT=Number(process.env.NATIVE_HOLDOUT_REPS||6);
const modes=['native','calibrated','current'],start=performance.now(),best={},scoresByBot={};let evaluations=0,searchMatches=0;
function play(seed,target,opponent,targetMode,genome,opponentMode,civA,civB,targetFirst){const m=new Match({mode:'bots',civA,civB,botA:targetFirst?target:opponent,botB:targetFirst?opponent:target},seed),tp=m.players.find(p=>p.id===(targetFirst?'A':'B')),rp=m.players.find(p=>p.id===(targetFirst?'B':'A'));tp.searchMode=targetMode;rp.searchMode=opponentMode;if(targetMode==='candidate')tp.searchGenome=genome;let n=0;while(!m.ended&&n++<1200)m.step(.5,true);return m.winner===tp.id?1:m.winner===null?.5:0;}
for(let ti=0;ti<bots.length;ti++){
 const bot=bots[ti],opponents=bots.filter(x=>x!==bot);let population=Array.from({length:POP},()=>randomGenome(bot)),top=null;
 for(let gen=0;gen<GENS;gen++){
  const ranked=population.map(g=>{let points=0,by={};for(let oi=0;oi<opponents.length;oi++){let sum=0;for(let mi=0;mi<modes.length;mi++)for(let r=0;r<REPS;r++){const seed=250000000+ti*10000000+gen*100000+oi*1000+mi*100+r,ca=civs[(r+oi+ti)%civs.length],cb=civs[(r*3+oi+1)%civs.length];sum+=play(seed,bot,opponents[oi],'candidate',g,modes[mi],ca,cb,true);sum+=play(seed,bot,opponents[oi],'candidate',g,modes[mi],cb,ca,false);}by[opponents[oi]]=sum/(REPS*modes.length*2);points+=sum;}const mean=points/(opponents.length*REPS*modes.length*2),worst=Math.min(...Object.values(by));return{genome:g,mean,worst,fitness:.75*mean+.25*worst};}).sort((a,b)=>b.fitness-a.fitness);
  evaluations+=ranked.length;searchMatches+=ranked.length*opponents.length*modes.length*REPS*2;if(!top||ranked[0].fitness>top.fitness)top=ranked[0];const next=ranked.slice(0,3).map(x=>x.genome);while(next.length<POP)next.push(mutate(bot,ranked[Math.floor(rng()*Math.min(6,ranked.length))].genome,gen<2?1:.7));population=next;
 }
 best[bot]=top;
}
const seedFamilies={prior:97000000,heldout:220000000},validation={};let validationMatches=0;
for(let ti=0;ti<bots.length;ti++){const bot=bots[ti],opponents=bots.filter(x=>x!==bot);validation[bot]={};for(let oi=0;oi<opponents.length;oi++){const opp=opponents[oi];validation[bot][opp]={};for(const oppMode of modes)for(const[family,seedBase]of Object.entries(seedFamilies)){const row={native:0,calibrated:0,current:0,tuned:0};for(let r=0;r<HOLDOUT;r++){const seed=seedBase+ti*10000000+oi*100000+['native','calibrated','current'].indexOf(oppMode)*10000+r,ca=civs[(r+oi+ti)%civs.length],cb=civs[(r*3+2)%civs.length];for(const side of [true,false]){const x=side?ca:cb,y=side?cb:ca;row.native+=play(seed,bot,opp,'native',null,oppMode,x,y,side);row.calibrated+=play(seed,bot,opp,'calibrated',null,oppMode,x,y,side);row.current+=play(seed,bot,opp,'current',null,oppMode,x,y,side);row.tuned+=play(seed,bot,opp,'candidate',best[bot].genome,oppMode,x,y,side);validationMatches+=4;}}validation[bot][opp][`${oppMode}_${family}`]=Object.fromEntries(Object.entries(row).map(([k,v])=>[k,Number((v/(HOLDOUT*2)).toFixed(4))]));}}}
const summary={};for(const bot of bots){const rows=Object.values(validation[bot]).flatMap(x=>Object.values(x)),avg=k=>rows.reduce((s,x)=>s+x[k],0)/rows.length,perOpponent={};for(const opp of bots.filter(x=>x!==bot)){const r=Object.values(validation[bot][opp]);perOpponent[opp]=Object.fromEntries(['native','calibrated','current','tuned'].map(k=>[k,r.reduce((s,x)=>s+x[k],0)/r.length]));}summary[bot]={means:Object.fromEntries(['native','calibrated','current','tuned'].map(k=>[k,avg(k)])),perOpponent};}
const elapsed=Number(((performance.now()-start)/1000).toFixed(2));
const result={title:'Per-strategy native branch tuning',createdAt:new Date().toISOString(),method:'Each strategy’s existing branch order and personality is preserved. Search changes only parameters used by that branch; opponent pool includes every other strategy in native, calibrated, and current production form. Candidate selection uses a mean/worst-opponent objective and common seed schedules within each generation. Validation uses a prior and a fresh held-out seed family.',budget:{elapsedSeconds:elapsed,maxSeconds:180,population:POP,generations:GENS,trainingRepetitionsPerOpponentPolicyAndSide:REPS,validationRepetitionsPerOpponentPolicyAndSide:HOLDOUT,candidateEvaluations:evaluations,searchMatches,validationMatches},bots:Object.fromEntries(bots.map(b=>[b,{genome:best[b].genome,searchMean:best[b].mean,searchWorst:best[b].worst,summary:summary[b],matchups:validation[b]}]))};
fs.writeFileSync(new URL('./native_branch_tuning_results.json',import.meta.url),JSON.stringify(result,null,2));
const pct=n=>`${(n*100).toFixed(1)}%`,lines=['# Ajuste de ramas nativas por estrategia','',`- Tiempo: **${elapsed}s** (límite: 180s).`,`- Búsqueda: ${evaluations} evaluaciones, ${searchMatches.toLocaleString('es-AR')} partidas.`,`- Validación reservada: ${validationMatches.toLocaleString('es-AR')} partidas en dos familias de semillas.`,`- Cada candidato conserva el orden nativo del bot y solo modifica los parámetros de su estrategia.`,`- Rivales: las otras ocho estrategias en tres estados: nativo, calibrado anterior y versión actual.`,`- Puntuación: victoria=1, empate=0,5, derrota=0; fitness de búsqueda combina media y peor rival.`, '', '| Bot | Nativo | Calibrado previo | Actual | Ramas nativas ajustadas | Δ vs actual |','|---|---:|---:|---:|---:|---:|'];
for(const b of bots){const x=summary[b].means;lines.push(`| ${b} | ${pct(x.native)} | ${pct(x.calibrated)} | ${pct(x.current)} | ${pct(x.tuned)} | ${pct(x.tuned-x.current)} |`);}lines.push('','Las mejoras pequeñas requieren más partidas para confirmarse. Antes de aplicarlas se revisa también el peor cruce y el resultado en ambas semillas.','','## Parámetros por bot','');for(const b of bots){lines.push(`### ${b}`,'',`- Mejor promedio de búsqueda: ${pct(best[b].mean)}; peor rival: ${pct(best[b].worst)}.`,`- Parámetros: ${Object.entries(best[b].genome).map(([k,v])=>`${k}=${v}`).join(', ')}.`,'- Validación por rival:');for(const[o,x]of Object.entries(summary[b].perOpponent))lines.push(`  - ${o}: nativo ${pct(x.native)}, calibrado ${pct(x.calibrated)}, actual ${pct(x.current)}, ajustado ${pct(x.tuned)}.`);lines.push('');}fs.writeFileSync(new URL('./native_branch_tuning_results.md',import.meta.url),lines.join('\n'));
console.log(JSON.stringify({elapsedSeconds:elapsed,evaluations,searchMatches,validationMatches,summary},null,2));
