import fs from 'node:fs';
import vm from 'node:vm';
import { performance } from 'node:perf_hooks';

// Re-optimize from the previous generation, then compare original/previous/new
// policies on paired, held-out old and fresh seed sets.
globalThis.window = globalThis;
for (const file of ['public/game/domain/random.js','public/game/domain/arena-config.js','public/game/domain/arena/match-engine.js'])
  vm.runInThisContext(fs.readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),{filename:file});
const prior=JSON.parse(fs.readFileSync(new URL('./all_bots_pvp_optimization.json',import.meta.url),'utf8'));
const {GAME_CONFIG,CIVILIZATIONS,BOTS}=FactoryWars.Config;
const Match=FactoryWars.Match, strategies=Object.keys(BOTS), civs=Object.keys(CIVILIZATIONS), original=Match.prototype.botDecision;
const ranges={ecoUntil:[55,165],ecoFactor:[1.15,2.3],factoryAfter:[10,80],defendAfter:[0,100],defendValue:[0,300],captureAfter:[25,135],captureChance:[.15,.9],attackAfter:[45,155],largeAfter:[75,185],largeBank:[230,680],sabotageAfter:[45,145],sabotageChance:[.1,.8],specialization:[0,2]};
const ints=new Set(['ecoUntil','factoryAfter','defendAfter','defendValue','captureAfter','attackAfter','largeAfter','largeBank','sabotageAfter','specialization']);
function policy(p){const g=p.tuneGenome,C=GAME_CONFIG,o=this.other(p),t=this.t,remain=C.matchDuration-t,threat=this.incoming(p),value=threat.reduce((s,x)=>s+x.damage,0)-this.shield(p);const can=k=>this.can(p,k),act=k=>this.act(p,k),payback=p.level>=4?Infinity:this.cost(p,'eco')/(C.economicLevels[p.level]-C.economicLevels[p.level-1]),grow=()=>can('eco')&&remain>payback*g.ecoFactor;const defend=()=>{if(t<g.defendAfter||value<=g.defendValue)return false;if(value>155&&can('defLarge'))return act('defLarge');return can('defSmall')&&act('defSmall');};if(!p.spec&&p.level>=C.specializationUnlockLevel&&t>28&&t<170){const s=['specIndustry','specArsenal','specControl'][g.specialization];if(can(s)&&this.rand()<.42&&act(s))return;}if(defend())return;if(grow()&&t<g.ecoUntil&&act('eco'))return;if(!p.factory&&t>=g.factoryAfter&&can('factory')&&act('factory'))return;if(t>=g.captureAfter&&this.rand()<g.captureChance&&can('capture')&&this.owner!==p.id&&remain>29&&act('capture'))return;if(t>=g.sabotageAfter&&o.level>=2&&this.rand()<g.sabotageChance&&can('sabotage')&&act('sabotage'))return;if(p.factory&&t>=g.attackAfter){if(t>=g.largeAfter&&p.bank>=g.largeBank&&can('large')&&act('large'))return;if(can('small')&&act('small'))return;}if(grow()&&act('eco'))return;return original.call(this,p);}
Match.prototype.botDecision=function(p){return p.tuneGenome?policy.call(this,p):original.call(this,p);};
let state=0x4e455847;const rng=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};
const clamp=(n,r)=>Math.max(r[0],Math.min(r[1],n));
function randomGenome(){const g={};for(const[k,r]of Object.entries(ranges)){const n=r[0]+rng()*(r[1]-r[0]);g[k]=ints.has(k)?Math.round(n):Number(n.toFixed(2));}return g;}
function mutate(parent,power=1){const g={...parent};for(const[k,r]of Object.entries(ranges))if(rng()<.36){const n=g[k]+(rng()+rng()+rng()-1.5)*(r[1]-r[0])*.2*power;g[k]=ints.has(k)?Math.round(clamp(n,r)):Number(clamp(n,r).toFixed(2));}return g;}

function play({seed,target,opponent,targetGenome,opponentGenome,civA,civB,targetFirst}){
 const targetBot=targetGenome?'TUNED_TARGET':target,opponentBot='TUNED_RIVAL';
 const botA=targetFirst?targetBot:opponentBot,botB=targetFirst?opponentBot:targetBot;
 const m=new Match({mode:'bots',civA,civB,botA,botB},seed);
 const tp=m.players.find(p=>p.id===(targetFirst?'A':'B')),rp=m.players.find(p=>p.id===(targetFirst?'B':'A'));
 if(targetGenome)tp.tuneGenome=targetGenome;rp.tuneGenome=opponentGenome;
 let n=0;while(!m.ended&&n++<1200)m.step(.5,true);
 return m.winner===tp.id?1:m.winner===null?.5:0;
}
const POP=Number(process.env.GEN_POPULATION||20),GENS=Number(process.env.GEN_GENERATIONS||5),REPS=Number(process.env.GEN_REPS||2),HOLDOUT=Number(process.env.GEN_HOLDOUT||12);
const start=performance.now(),fresh={};let evaluations=0,searchMatches=0;
for(let ti=0;ti<strategies.length;ti++){
 const target=strategies[ti],opponents=strategies.filter(x=>x!==target),priorGenome=prior.bots[target].bestGenome;
 let population=[priorGenome,...Array.from({length:POP-1},(_,i)=>i<Math.floor((POP-1)/2)?mutate(priorGenome,.9):randomGenome())],best=null;
 const evaluate=(g,gen,ix)=>{let total=0,by={};for(let oi=0;oi<opponents.length;oi++){let score=0;for(let r=0;r<REPS;r++){const seed=120000000+ti*10000000+gen*100000+oi*20+r,ca=civs[(r+oi+ti)%civs.length],cb=civs[(r*3+oi+1)%civs.length],og=prior.bots[opponents[oi]].bestGenome;score+=play({seed,target,opponent:opponents[oi],targetGenome:g,opponentGenome:og,civA:ca,civB:cb,targetFirst:true});score+=play({seed,target,opponent:opponents[oi],targetGenome:g,opponentGenome:og,civA:cb,civB:ca,targetFirst:false});}by[opponents[oi]]=score/(REPS*2);total+=score;}const mean=total/(opponents.length*REPS*2),worst=Math.min(...Object.values(by));return{genome:g,mean,worst,fitness:.75*mean+.25*worst,by};};
 for(let gen=0;gen<GENS;gen++){const ranked=population.map((g,i)=>evaluate(g,gen,i)).sort((a,b)=>b.fitness-a.fitness);evaluations+=ranked.length;searchMatches+=ranked.length*opponents.length*REPS*2;if(!best||ranked[0].fitness>best.fitness)best=ranked[0];const next=ranked.slice(0,4).map(x=>x.genome);while(next.length<POP)next.push(mutate(ranked[Math.floor(rng()*Math.min(8,ranked.length))].genome,gen<2?1:.72));population=next;}
 fresh[target]=best.genome;
}

// The old set reproduces the previous report's holdout schedule. The new set is
// held apart from the search and uses the same pairings/mirror schedule.
const validation={};let validationMatches=0;
for(let ti=0;ti<strategies.length;ti++){const target=strategies[ti],opponents=strategies.filter(x=>x!==target),rows={};for(let oi=0;oi<opponents.length;oi++){const opponent=opponents[oi],og=prior.bots[opponent].bestGenome,oldScores={previous:0,fresh:0,original:0},newScores={previous:0,fresh:0,original:0};for(let r=0;r<HOLDOUT;r++){const ca=civs[(r+oi+ti)%civs.length],cb=civs[(r*3+2)%civs.length],oldSeed=97000000+ti*1000000+oi*1000+r,newSeed=150000000+ti*1000000+oi*1000+r;for(const side of [true,false]){const x=side?ca:cb,y=side?cb:ca;for(const [k,g]of [['previous',prior.bots[target].bestGenome],['fresh',fresh[target]],['original',null]]){oldScores[k]+=play({seed:oldSeed,target,opponent,targetGenome:g,opponentGenome:og,civA:x,civB:y,targetFirst:side});newScores[k]+=play({seed:newSeed,target,opponent,targetGenome:g,opponentGenome:og,civA:x,civB:y,targetFirst:side});validationMatches+=2;}}}const divisor=HOLDOUT*2;rows[opponent]={old:Object.fromEntries(Object.entries(oldScores).map(([k,v])=>[k,Number((v/divisor).toFixed(4))])),fresh:Object.fromEntries(Object.entries(newScores).map(([k,v])=>[k,Number((v/divisor).toFixed(4))]))};}validation[target]=rows;}
const stats={};for(const target of strategies){const vs=Object.values(validation[target]);const oldPer=Object.fromEntries(['previous','fresh','original'].map(k=>[k,vs.reduce((s,x)=>s+x.old[k],0)/vs.length]));const newPer=Object.fromEntries(['previous','fresh','original'].map(k=>[k,vs.reduce((s,x)=>s+x.fresh[k],0)/vs.length]));stats[target]={oldSeed:oldPer,newSeed:newPer,transferDelta:Number((newPer.fresh-oldPer.fresh).toFixed(4)),freshVsPriorOld:Number((oldPer.fresh-oldPer.previous).toFixed(4)),freshVsOriginalOld:Number((oldPer.fresh-oldPer.original).toFixed(4)),freshVsPriorNew:Number((newPer.fresh-newPer.previous).toFixed(4)),freshVsOriginalNew:Number((newPer.fresh-newPer.original).toFixed(4))};}
const elapsed=Number(((performance.now()-start)/1000).toFixed(2));
const result={title:'Cross-seed validation of next PvP bot generation',createdAt:new Date().toISOString(),method:'Re-optimized every bot starting from the prior genome using a new training seed family; each candidate faced the previous generation’s tuned opponents. Then compared original, previous tuned, and new tuned policies on two separate paired holdout seed sets: previous validation family and a fresh family. Both sides/civilizations are matched.',budget:{elapsedSeconds:elapsed,maxSeconds:180,population:POP,generations:GENS,trainingRepetitionsPerOpponentAndSide:REPS,validationRepetitionsPerOpponentAndSide:HOLDOUT,candidateEvaluations:evaluations,searchMatches,validationMatches},bots:Object.fromEntries(strategies.map(s=>[s,{genome:fresh[s],validation:validation[s],summary:stats[s]}]))};
fs.writeFileSync(new URL('./bot_generation_cross_seed.json',import.meta.url),JSON.stringify(result,null,2));
const pct=x=>`${(100*x).toFixed(1)}%`,lines=['# Validación cruzada entre generaciones de bots PvP','',`- Tiempo: **${elapsed}s** (máximo: 180s)`,`- Reoptimización: ${evaluations} evaluaciones y ${searchMatches.toLocaleString('es-AR')} partidas de búsqueda.`,`- Validación: ${validationMatches.toLocaleString('es-AR')} partidas; mismo rival/civilización/lado para comparar original, anterior y nuevo.`,`- Semilla nueva para entrenar; validación en la familia de semilla anterior y otra familia nueva, ambas fuera del entrenamiento.`,`- Motor base: sin módulos industriales, doctrinas ni bonificaciones persistentes.`,`- La nueva generación usa un orden compartido de decisiones parametrizado; la versión anterior también. No equivale a reescribir y optimizar internamente cada rama nativa.`, '', '| Bot | Anterior · sem. previa | Nuevo · sem. previa | Original · sem. previa | Δ nueva−anterior | Anterior · sem. nueva | Nuevo · sem. nueva | Original · sem. nueva | Δ nueva−anterior |','|---|---:|---:|---:|---:|---:|---:|---:|---:|'];
for(const s of strategies){const x=stats[s];lines.push(`| ${s} | ${pct(x.oldSeed.previous)} | ${pct(x.oldSeed.fresh)} | ${pct(x.oldSeed.original)} | ${pct(x.freshVsPriorOld)} | ${pct(x.newSeed.previous)} | ${pct(x.newSeed.fresh)} | ${pct(x.newSeed.original)} | ${pct(x.freshVsPriorNew)} |`);}
lines.push('','Cambio positivo indica mejor puntuación media de la nueva versión frente a la anterior. Victoria=1, empate=0, derrota=0. Son estimaciones; confirmar cruces individuales antes de promover.','','## Cruces por bot','');for(const s of strategies){lines.push(`### ${s}`,'',...Object.entries(validation[s]).map(([opp,x])=>`- ${opp}: semilla previa: anterior ${pct(x.old.previous)}, nueva ${pct(x.old.fresh)}, original ${pct(x.old.original)}; semilla nueva: anterior ${pct(x.fresh.previous)}, nueva ${pct(x.fresh.fresh)}, original ${pct(x.fresh.original)}.`),'');}fs.writeFileSync(new URL('./bot_generation_cross_seed.md',import.meta.url),lines.join('\n'));
console.log(JSON.stringify({elapsedSeconds:elapsed,evaluations,searchMatches,validationMatches,bots:stats},null,2));
